export const company = {
  name: 'Nanotechnology IT Solutions',
  shortName: 'Nanotechnology',
  tagline: 'Connect. Secure. Support. Transform.',
  phone: '072 825 4536',
  phoneHref: 'tel:+27728254536',
  whatsappNumber: '27728254536',
  whatsappUrl: 'https://wa.me/27728254536',
  email: 'info@nanotechnology6.co.za',
  address: '409 Imam Haron Road, Lansdowne, Cape Town',
  hours: 'Monday–Friday, 08:00–17:00',
  serviceArea: 'Cape Town and surrounding areas',
  website: 'https://nanotechnology6.co.za',
  supportEmail: '',
  mapsUrl: 'https://www.google.com/maps/search/?api=1&query=409+Imam+Haron+Road+Lansdowne+Cape+Town',
  social: { facebook: '', linkedin: '', instagram: '' },
} as const
