export const company = {
  name: 'Nanotechnology IT Solutions',
  shortName: 'Nanotechnology',
  tagline: 'Connect. Secure. Support. Transform.',
  phone: '087 265 3701',
  phoneHref: 'tel:+27872653701',
  whatsappNumber: '27728254536',
  whatsappUrl: 'https://wa.me/27728254536',
  email: 'info@nanotechnology6.co.za',
  address: '409 Imam Haron Road, Lansdowne, Cape Town',
  hours: 'Monday–Friday, 08:00–17:00',
  serviceArea: 'South Africa Nationwide',
  headOfficeCity: 'Cape Town',
  country: 'South Africa',
  nationwideSupport: true,
  serviceAreaStatement: 'Serving schools, universities, colleges, QCTO-accredited providers, training organisations and skills-development institutions across South Africa.',
  nationwideServicesStatement: 'Nationwide IT infrastructure, education technology, cloud, software and creative services.',
  website: 'https://nanotechnology6.co.za',
  supportEmail: '',
  mapsUrl: 'https://www.google.com/maps/search/?api=1&query=409+Imam+Haron+Road+Lansdowne+Cape+Town',
  social: { facebook: '', linkedin: '', instagram: '' },
} as const
